version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    container_name: grok-sdr-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: grok_sdr
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - grok-network

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: grok-sdr-backend
    ports:
      - "3001:3001"
    environment:
      DATABASE_URL: postgresql://postgres:postgres@postgres:5432/grok_sdr
      NODE_ENV: development
      GROK_API_KEY: ${GROK_API_KEY}
      GROK_API_URL: ${GROK_API_URL:-https://api.x.ai/v1}
      JWT_SECRET: ${JWT_SECRET:-default_jwt_secret_change_in_production}
    depends_on:
      - postgres
    volumes:
      - ./backend:/app
      - /app/node_modules
    networks:
      - grok-network
    command: sh -c "npx prisma migrate deploy && npm run dev"

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: grok-sdr-frontend
    ports:
      - "3000:3000"
    environment:
      NEXT_PUBLIC_API_URL: http://localhost:3001
    depends_on:
      - backend
    volumes:
      - ./frontend:/app
      - /app/node_modules
      - /app/.next
    networks:
      - grok-network
    command: npm run dev

volumes:
  postgres_data:

networks:
  grok-network:
    driver: bridge